[project]
name = "albumart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sandy Sim", email = "sandy@hobosuit.com" }
]
requires-python = ">=3.13"
dependencies = [
    "audioop-lts>=0.2.2",
    "numpy>=2.5.3",
    "pygame>=2.6.1",
    "requests>=2.34.2",
    "scipy>=1.18.1",
    "shazamio>=0.8.1",
    "sounddevice>=0.5.6",
    "soundfile>=0.14.0",
]

[project.scripts]
albumart = "albumart:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
